apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-cluster
spec:
  replicas: 5
  selector:
    matchLabels:
      app: akka-simple-cluster
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: akka-simple-cluster
    spec:
      serviceAccountName: akka-simple-cluster
      containers:
      - image: softwaremill/akka-simple-cluster-k8s:0.0.1-SNAPSHOT
        imagePullPolicy: IfNotPresent
        name: akka-simple-cluster
        env:
          - name: HOSTNAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP
          - name: "DYN_JAVA_OPTS"
            value: "-Dakka.remote.netty.tcp.hostname=${HOSTNAME//./-}.default.pod.cluster.local -Dakka.management.http.hostname=${HOSTNAME//./-}.default.pod.cluster.local"
        ports:
        - name: remoting
          containerPort: 2551
        - name: api
          containerPort: 8080
        - name: management
          containerPort: 8558
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20